name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
    # First step (unnamed here) is to checkout to the branch that triggered the event
    - uses: actions/checkout@v3

    # Second step: install python 3.12.9
    - name: Set up Python 3.12.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.12.9"
